### ISSUE TITLE
Tracking issue: release 1.0.0 that includes critical-section support

### ISSUE THREAD

**Issue by taiki-e** [taiki-e/portable-atomic#61]
I said in past:

> Even if the library's API did not have the CS API, I believe CS would always be considered a public dependency of the library, since updating the CS version or removing CS impls or dependency on CS could break downstream builds.

So, if both portable-atomic 0.3 and portable-atomic 1 support CS, updating from portable-atomic 0.3 to portable-atomic 1 may need to be considered a breaking change because it changes the version of the portable-atomic that needs to enable the CS feature in downstream.

This can be addressed by releasing the first portable-atomic with CS support as portable-atomic 1 and never releasing major version 2[^1]. The portable-atomic's API is stable enough that no changes should be necessary except for the removal of the outline-atomics feature that is no longer used.

### TODO

- [x] merge https://github.com/taiki-e/portable-atomic/pull/51; done
- [x] remove the outline-atomics feature that is no longer used; done in https://github.com/taiki-e/portable-atomic/commit/fb5bc25b2842b45ce37bf7381fb8ac58452d01c2
- [x] (adjust docs) https://github.com/taiki-e/portable-atomic/compare/aed4e1758ab2a015edb2a0784f90d3f209a200df...a6b3b95e218942170be864f772a04f7e6dc46e0b

Is there anything else you think is needed for this release?

ETA: I think I can finish this during this weekend.

[^1]: Even if critical-section 2.0 is released, it can be supported with a feature like critical-section2.

**Comment by notgull** [comment]
How will this be related to a potential release of `portable-atomic-util`, if any?

We may also want to add a general purpose `Atomic<T>` type, similar to crossbeam's `AtomicCell` (maybe better for `portable-atomic-util`?) #1 

I think this crate is in a good state as-is.

**Comment by taiki-e** [comment]
> How will this be related to a potential release of `portable-atomic-util`, if any?

Good point. As for portable-atomic-util, I would like to give it a different version number than the main portable-atomic crate, as said in https://github.com/taiki-e/portable-atomic/issues/43. i.e., the portable-atomic will be 1.0, but the portable-atomic-util will be released as 0.1. (It is a bug in our release infrastructure that both crates currently use the same version number, and I would like to release portable-atomic-util 0.1 once that is fixed.)

> We may also want to add a general purpose `Atomic<T>` type, similar to crossbeam's `AtomicCell` (maybe better for `portable-atomic-util`?) #1

Yeah, as for generic `Atomic<T>`, I think it would make sense to add it to the portable-atomic-util.
(Without AtomicMaybeUninit it cannot be implemented without limitations or potential UB. And it is not yet clear to me what the best API is to minimize that limitation as much as possible.)

**Comment by taiki-e** [comment]
Published:
- https://crates.io/crates/portable-atomic/1.0.0
- https://crates.io/crates/portable-atomic-util/0.1.0
